---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-byte-order-marker
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-yaml
        files: .*\.(yaml|yml)$
  - repo: https://gitlab.com/pycqa/flake8.git
    rev: 3.9.0
    hooks:
      - id: flake8
  - repo: https://github.com/openstack-dev/bashate.git
    rev: 2.0.0
    hooks:
      - id: bashate
        entry: bashate --error . --ignore=E006,E040,E042
        # Run bashate check for all bash scripts
        # Ignores the following rules:
        # E006: Line longer than 79 columns (as many scripts use jinja
        #       templating, this is very difficult)
        # E040: Syntax error determined using `bash -n` (as many scripts
        #       use jinja templating, this will often fail and the syntax
        #       error will be discovered in execution anyway)
  - repo: https://github.com/PyCQA/pylint
    rev: pylint-2.7.2
    hooks:
      - id: pylint
