tcib_actions:
- run: >-
    dnf install -y crudini &&
    crudini --del /etc/dnf/dnf.conf main override_install_langs &&
    crudini --set /etc/dnf/dnf.conf main clean_requirements_on_remove True &&
    crudini --set /etc/dnf/dnf.conf main exactarch 1 &&
    crudini --set /etc/dnf/dnf.conf main gpgcheck 1 &&
    crudini --set /etc/dnf/dnf.conf main install_weak_deps False &&
    crudini --set /etc/dnf/dnf.conf main installonly_limit 0 &&
    crudini --set /etc/dnf/dnf.conf main keepcache 0 &&
    crudini --set /etc/dnf/dnf.conf main obsoletes 1 &&
    crudini --set /etc/dnf/dnf.conf main plugins 1 &&
    crudini --set /etc/dnf/dnf.conf main skip_missing_names_on_install False &&
    crudini --set /etc/dnf/dnf.conf main tsflags nodocs
- run: groupadd --force --gid 42400 kolla && useradd -l -M --shell /usr/sbin/nologin --uid 42400 --gid 42400 kolla
- run: touch /usr/local/bin/kolla_extend_start && chmod 755 /usr/local/bin/kolla_extend_start
- copy: /usr/share/tripleo-common/container-images/kolla/base/set_configs.py /usr/local/bin/kolla_set_configs
- run: chmod 755 /usr/local/bin/kolla_set_configs
- copy: /usr/share/tripleo-common/container-images/kolla/base/start.sh /usr/local/bin/kolla_start
- run: chmod 755 /usr/local/bin/kolla_start
- copy: /usr/share/tripleo-common/container-images/kolla/base/httpd_setup.sh /usr/local/bin/kolla_httpd_setup
- run: chmod 755 /usr/local/bin/kolla_httpd_setup
- copy: /usr/share/tripleo-common/container-images/kolla/base/sudoers /etc/sudoers
- run: chmod 440 /etc/sudoers
- run: sed -ri '/-session(\s+)optional(\s+)pam_systemd.so/d' /etc/pam.d/system-auth
- run: sed -ri '/^(passwd:|group:)/ s/systemd//g' /etc/nsswitch.conf
- run: dnf install -y {{ tcib_packages['common'] | join(' ') }}
- run: mkdir -p /openstack
- run: dnf update -y && dnf clean all && rm -rf /var/cache/dnf
tcib_cmd: kolla_start
tcib_entrypoint: dumb-init --single-child --
tcib_envs:
  LANG: en_US.UTF-8
  container: oci
tcib_gather_files: '{{ lookup(''fileglob'', ''/usr/share/tripleo-common/container-images/kolla/base/*'', wantlist=True) }}'
tcib_labels:
  maintainer: OpenStack TripleO team
  kolla_version: none
tcib_packages:
  common:
  - ca-certificates
  - curl
  - dumb-init
  - glibc-langpack-en
  - iscsi-initiator-utils
  - openstack-selinux
  - openstack-tripleo-common-container-base
  - procps-ng
  - python3
  - rsync
  - socat
  - sudo
  - tar
  - util-linux-user
tcib_stopsignal: SIGTERM
