tcib_actions:
- run: if [ -f "/etc/yum.repos.d/ubi.repo" ]; then rm -f /etc/yum.repos.d/ubi.repo && dnf clean all && rm -rf /var/cache/dnf; fi
- run: >-
    dnf install -y crudini &&
    crudini --del /etc/dnf/dnf.conf main override_install_langs &&
    crudini --set /etc/dnf/dnf.conf main clean_requirements_on_remove True &&
    crudini --set /etc/dnf/dnf.conf main exactarch 1 &&
    crudini --set /etc/dnf/dnf.conf main gpgcheck 1 &&
    crudini --set /etc/dnf/dnf.conf main install_weak_deps False &&
    if [ '{{ tcib_distro }}' == 'centos' ];then crudini --set /etc/dnf/dnf.conf main best False; fi &&
    crudini --set /etc/dnf/dnf.conf main installonly_limit 0 &&
    crudini --set /etc/dnf/dnf.conf main keepcache 0 &&
    crudini --set /etc/dnf/dnf.conf main obsoletes 1 &&
    crudini --set /etc/dnf/dnf.conf main plugins 1 &&
    crudini --set /etc/dnf/dnf.conf main skip_missing_names_on_install False &&
    crudini --set /etc/dnf/dnf.conf main tsflags nodocs
- run: >-
    if [ '{{ tcib_distro }}' == 'rhel' ] && [ '{{ tcib_release }}' == '8' ]; then
    {%- if "el" ~ tcib_release in tcib_packages.modules %}
     {% for item in tcib_packages.modules["el" ~ tcib_release] %}{% set key, value = (item.items() | list).0 %}dnf module -y {{ key }} {{ value }}; {% endfor %}
    {%- else %}
      echo "WARNING: No modules defined for el{{ tcib_release}}";
    {%- endif %}
    fi
- run: dnf install -y openstack-tripleo-common-containers
- run: cp /usr/share/openstack-tripleo-common-containers/container-images/kolla/base/uid_gid_manage.sh /usr/local/bin/uid_gid_manage
- run: chmod 755 /usr/local/bin/uid_gid_manage
- run: bash /usr/local/bin/uid_gid_manage kolla hugetlbfs libvirt qemu
- run: touch /usr/local/bin/kolla_extend_start && chmod 755 /usr/local/bin/kolla_extend_start
- run: cp /usr/share/openstack-tripleo-common-containers/container-images/kolla/base/set_configs.py /usr/local/bin/kolla_set_configs
- run: chmod 755 /usr/local/bin/kolla_set_configs
- run: cp /usr/share/openstack-tripleo-common-containers/container-images/kolla/base/start.sh /usr/local/bin/kolla_start
- run: chmod 755 /usr/local/bin/kolla_start
- run: cp /usr/share/openstack-tripleo-common-containers/container-images/kolla/base/httpd_setup.sh /usr/local/bin/kolla_httpd_setup
- run: chmod 755 /usr/local/bin/kolla_httpd_setup
- run: cp /usr/share/openstack-tripleo-common-containers/container-images/kolla/base/sudoers /etc/sudoers
- run: chmod 440 /etc/sudoers
- run: >-
    if [ '{{ tcib_release }}' == '8' ];then
    sed -ri '/-session(\s+)optional(\s+)pam_systemd.so/d' /etc/pam.d/system-auth &&
    dnf install -y curl; fi
- run: sed -ri '/^(passwd:|group:)/ s/systemd//g' /etc/nsswitch.conf
- run: dnf install -y {{ tcib_packages['common'] | join(' ') }}
- run: >-
    if [ '{{ tcib_release }}' == '9' ];then
    dnf -y reinstall which &&
    rpm -e --nodeps tzdata &&
    dnf -y install tzdata; fi
- run: mkdir -p /openstack
- run: >-
    if [ '{{ tcib_distro }}' == 'centos' ];then
    if [ -n "$(rpm -qa redhat-release)" ];then rpm -e --nodeps redhat-release; fi ;
    dnf -y install centos-stream-release; fi
- run: dnf update --excludepkgs redhat-release -y && dnf clean all && rm -rf /var/cache/dnf
tcib_cmd: kolla_start
tcib_entrypoint: dumb-init --single-child --
tcib_envs:
  LANG: en_US.UTF-8
  container: oci
tcib_labels:
  maintainer: OpenStack TripleO team
  tcib_managed: True
tcib_packages:
  common:
  - ca-certificates
  - dumb-init
  - glibc-langpack-en
  - iscsi-initiator-utils
  - openstack-tripleo-common-containers
  - openstack-tripleo-common-container-base
  - procps-ng
  - python3
  - rsync
  - socat
  - sudo
  - tar
  - util-linux-user
  - which
  modules:
    el8:
      - disable: container-tools:rhel8
      - disable: virt:rhel
      - enable: container-tools:{{ tcib_rhel_modules['container-tools'] | default('3.0') }}
      - enable: mariadb:{{ tcib_rhel_modules['mariadb'] | default('10.3') }}
      - enable: virt:{{ tcib_rhel_modules['virt'] | default('av') }}
      - enable: redis:{{ tcib_rhel_modules['redis'] | default('5') }}
      - enable: nodejs:{{ tcib_rhel_modules['nodejs'] | default('14') }}
    el9:
      - disable: virt:rhel
      - enable: virt:{{ tcib_rhel_modules['virt'] | default('av') }}
      - enable: redis:{{ tcib_rhel_modules['redis'] | default('5') }}
      - enable: mariadb:{{ tcib_rhel_modules['mariadb'] | default('10.5') }}
tcib_stopsignal: SIGTERM
