#!/bin/sh

. ${HEALTHCHECK_SCRIPTS:-/usr/share/openstack-tripleo-common/healthcheck}/common.sh

bind_host=$(get_config_val /etc/heat/heat.conf heat_api bind_host 127.0.0.1)
bind_port=$(get_config_val /etc/heat/heat.conf heat_api bind_port 8004)
healthcheck_curl http://${bind_host}:${bind_port}/
