#!/bin/bash

. ${HEALTHCHECK_SCRIPTS:-/usr/share/openstack-tripleo-common/healthcheck}/common.sh

bind_host=$(get_config_val /etc/nova/nova.conf vnc novncproxy_host 127.0.0.1)
bind_port=$(get_config_val /etc/nova/nova.conf vnc novncproxy_port 6080)

healthcheck_curl http://${bind_host}:${bind_port}/
