#!/bin/bash

. ${HEALTHCHECK_SCRIPTS:-/usr/share/openstack-tripleo-common/healthcheck}/common.sh

conf=/etc/swift/account-server.conf
cache=/var/cache/swift/account.recon

if ps -ef | grep --quiet [s]wift-account-server; then
    if ! crudini --get $conf pipeline:main pipeline | grep -q healthcheck; then
        echo "healthcheck is not available" >&2
        exit 0
    fi

    # swift-account-server is still eventlet
    bind_host=$(wrap_ipv6 $(get_config_val $conf DEFAULT bind_ip 127.0.0.1))
    bind_port=$(get_config_val $conf DEFAULT bind_port 6002)
    healthcheck_curl http://${bind_host}:${bind_port}/healthcheck
elif ps -ef | grep --quiet [s]wift-account-replicator; then
    check_swift_interval account-replicator
fi
